# Generated by Django 4.2.3 on 2024-08-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_school_text_alter_profile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_text',
        ),
    ]
