# Generated by Django 4.2.3 on 2024-08-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_school_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(
                to='users.School',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                default=None
            ),
        )
    ]
