# Generated by Django 4.2.3 on 2024-08-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_school'),
        ('users', '0007_fix_school_field'),
    ]

    operations = [
    ]
