# Generated by Django 4.2.3 on 2024-06-19 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience1', models.CharField(default='mcd', max_length=50)),
                ('experience2', models.CharField(default='tagerty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(default='New York, NY', max_length=50)),
                ('category', models.CharField(choices=[('academic_enrichment', 'Academic Enrichment'), ('extracurricular_activities', 'Extracurricular Activities'), ('stem', 'STEM'), ('internships_work_experience', 'Internships and Work Experience'), ('community_service_volunteering', 'Community Service and Volunteering'), ('leadership_development', 'Leadership Development'), ('college_career_readiness', 'College and Career Readiness'), ('personal_development', 'Personal Development'), ('cultural_global_awareness', 'Cultural and Global Awareness'), ('health_wellness', 'Health and Wellness'), ('arts_creativity', 'The Arts and Creativity')], default='academic_enrichment', max_length=50)),
                ('background', models.ImageField(default='default.jpg', upload_to='background_images')),
                ('responsibilities', models.TextField(default='Add responsibilities for this responsibility')),
                ('grade', models.CharField(default='10th Grade', max_length=35)),
                ('length', models.CharField(choices=[('less_than_a_week', 'Less than a week'), ('one_week_to_four', '1-4 weeks'), ('one_month_to_three', '1-3 months'), ('three_month_to_six', '3-6 months'), ('six_month_plus', '6+ months')], default='less_than_a_week', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('like', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('num_applications', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25)),
                ('contact', models.TextField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
